/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: "#131313",
        error: "#ffb4ab",
        errorContainer: "#93000a",
        inverseOnSurface: "#313030",
        inversePrimary: "#9d4324",
        inverseSurface: "#e5e2e1",
        onBackground: "#e5e2e1",
        onError: "#690005",
        onErrorContainer: "#ffdad6",
        onPrimary: "#5d1800",
        onPrimaryContainer: "#521400",
        onPrimaryFixed: "#390b00",
        onPrimaryFixedVariant: "#7e2c0e",
        onSecondary: "#4d2618",
        onSecondaryContainer: "#e8aa97",
        onSecondaryFixed: "#331106",
        onSecondaryFixedVariant: "#673b2d",
        onSurface: "#e5e2e1",
        onSurfaceVariant: "#dcc1b8",
        onTertiary: "#003737",
        onTertiaryContainer: "#002f30",
        onTertiaryFixed: "#002020",
        onTertiaryFixedVariant: "#004f50",
        outline: "#a48b84",
        outlineVariant: "#56423c",
        primary: "#ffb59d",
        primaryContainer: "#dc7350",
        primaryFixed: "#ffdbd0",
        primaryFixedDim: "#ffb59d",
        secondary: "#f7b8a4",
        secondaryContainer: "#6a3d2f",
        secondaryFixed: "#ffdbd0",
        secondaryFixedDim: "#f7b8a4",
        surface: "#131313",
        surfaceBright: "#3a3939",
        surfaceContainer: "#201f1f",
        surfaceContainerHigh: "#2a2a2a",
        surfaceContainerHighest: "#353534",
        surfaceContainerLow: "#1c1b1b",
        surfaceContainerLowest: "#0e0e0e",
        surfaceDim: "#131313",
        surfaceTint: "#ffb59d",
        surfaceVariant: "#353534",
        tertiary: "#6cd7d8",
        tertiaryContainer: "#28a0a1",
        tertiaryFixed: "#89f4f4",
        tertiaryFixedDim: "#6cd7d8"
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'xl': '1.5rem',
      }
    },
  },
  plugins: [],
};
